# PyTorch Fundamentals: Matricies

## Matrix Basics

In [1]:
import numpy as np

In [2]:
arr = [[1,2], [3,4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [6]:
np.ones((2,2,))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [7]:
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [8]:
np.random.rand(2, 2)

array([[ 0.20081493,  0.78909926],
       [ 0.57139511,  0.10396615]])

In [9]:
torch.rand(2, 2)


 0.3288  0.8443
 0.9521  0.4809
[torch.FloatTensor of size 2x2]

## Seed for Reproducability

In [10]:
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [11]:
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [12]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [13]:
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [14]:
torch.rand(2, 2)


 0.3074  0.6341
 0.4901  0.8964
[torch.FloatTensor of size 2x2]

In [15]:
if torch.cuda.is_available():
    toch.cuda.manual_seed_all(0)

## Torch to NumPy Bridge

### NumPy to Torch

In [44]:
np_array = np.ones((2, 2))

In [45]:
np_array

array([[ 1.,  1.],
       [ 1.,  1.]])

In [18]:
torch_tensor = torch.from_numpy(np_array)

In [19]:
torch_tensor


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [20]:
type(torch_tensor)

torch.DoubleTensor

In [21]:
np_array_new = np.ones((2, 2), dtype=np.int8)

In [22]:
import traceback

try:
    torch.from_numpy(np_array_new)
except RuntimeError as e:
    traceback.print_exc()

Traceback (most recent call last):
  File "<ipython-input-22-235b0adda244>", line 4, in <module>
    torch.from_numpy(np_array_new)
RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.


In [23]:
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [24]:
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [25]:
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [26]:
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [27]:
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

### Torch to NumPy

In [28]:
torch_tensor = torch.ones(2, 2)
type(torch_tensor)

torch.FloatTensor

In [29]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

## GPU and CPU Toggling

In [30]:
tensor_cpu = torch.ones(2, 2)
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [31]:
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## Basic Mathematical Tensor Operations

In [33]:
a = torch.ones(2, 2)
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [34]:
a.size()

torch.Size([2, 2])

In [35]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [36]:
a.view(4).size()

torch.Size([4])

In [48]:
a = torch.ones(2, 2)
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [39]:
b = torch.ones(2, 2)
b


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [40]:
c = a + b
c


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [41]:
torch.add(a, b)


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [50]:
print(c)
c.add_(a)
print(c)


 3  3
 3  3
[torch.FloatTensor of size 2x2]


 4  4
 4  4
[torch.FloatTensor of size 2x2]



In [57]:
print(a)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [58]:
a-b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [59]:
a.sub(b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [60]:
print(a)
a.sub_(b)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [62]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [63]:
a * b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [64]:
torch.mul(a, b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [65]:
print(a)
a.mul_(b)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [71]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [72]:
b / a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [73]:
b.div(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [74]:
print(b)
b.div_(a)
print(b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [75]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [76]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [77]:
try:
    a.mean(dim=1)
except RuntimeError as e:
    traceback.print_exc()

Traceback (most recent call last):
  File "<ipython-input-77-9aa489b3ff6f>", line 2, in <module>
    a.mean(dim=1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)


In [80]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [81]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

In [83]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]